### ISSUE TITLE
Async interface

### ISSUE THREAD

**Issue by patrick-zippenfenig** [kirilltitov/FDBSwift#1]
Hi,

thanks for the heads up on https://github.com/apple/foundationdb/issues/204. I see you already have the async interface on your ToDo list. I would recommend to primarily focus on the async interface. For synchronous access a simple ``wait()`` function should be fine.

Swift NIO has a great concept for asynchronous futures and the first web-frameworks adapt this concept (e.g. [Vapor 3](https://docs.vapor.codes/3.0/getting-started/async/)).

Would it be possible to have Swift NIO style Futures and Promises?

Thanks!

**Comment by kirilltitov** [comment]
Absolutely! I will expose native FoundationDB `future`s mechanism (e.g. `fdb_future_set_callback` etc), and also I'm gonna create an additional repo with Swift-NIO integration (NIO's `EventLoopFuture`s), as I'm already using this repo with my Swift-NIO server :)

Still not sure about the API though. I wouldn't really like to create overloaded methods like
`get(...) -> Bytes?`
`get(...) -> Future<Bytes?>`
as those force to explicitly set variable type. Considering creating methods like
`asyncGet(...) -> Future<Bytes?>`
but that feels somewhat ugly.

TBH, this hesitation is the main reason I haven't implemented async yet :)

**Comment by patrick-zippenfenig** [comment]
As foundationDB is designed to be used in an asynchronous way, I would only use the async interface. I saw you implicitly call wait() in the code anyway.

```swift
get(...) -> Future<Data>

let myData = fdb->get(...).wait()
```

**Comment by kirilltitov** [comment]
OK, so I decided to utilize `Swift-NIO` in this very repository. I've considered creating independent repo `FDBSwift-NIO`, but it turned out to be quite impractical. Also using native `Future`s (genericized to `<Bytes>`, `<[KeyValue]>` and `<Void>`) directly is highly uncomfortable. NIO-s futures on the other hand is exactly what we all need. I think, I'll finish it within the next week (you can see WIP in `develop` branch) (be warned tho, it compiles, but unstable and crashes randomly)

**Comment by kirilltitov** [comment]
Almost done, lads. Writing unit tests for NIO futures. Gonna need major version bump though.
